services:
  - type: web
    name: whisperframe-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    scaling:
      minInstances: 0
      maxInstances: 1 